[project]
name = "lactationcurve"
version = "0.1.1"
license = "MIT"
description = "Lactation curve fitting and analysis library"
readme = "README.md"
requires-python = ">= 3.12, < 3.13"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering",
]
dependencies = [
    "numpy>=2.4.0",
    "pandas>=2.3.3",
    "scipy>=1.16.3",
    "sympy>=1.14.0",
    # "matplotlib>=3.10.8",
    "requests>=2.32.5",
]

[dependency-groups]
dev = ["pytest>=8.0.0", "ruff>=0.1.0", "python-dotenv>=1.0.0"]

[project.urls]
Repository = "https://github.com/Bovi-analytics/lactation-curves"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/lactationcurve"]

[tool.ruff]
target-version = "py312"
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["../../../tests"]

[tool.setuptools.package-data]
lactation = ["README.md"]
